---
#
# Installs Nginx
#
# Install Nginx
- name: Update cache repositories and install Nginx
  apt:
    name: nginx
    update_cache: yes
# Create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file: 
    path: /etc/nginx/conf.d/
    state: directory
    mode: 0755
# cofigure kibana.conf with a FQDN(Fully Qualified Domain Name)
- name: Setup Nginx reverse proxy for kibana
  template:
    src: kibana.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
# Enable nginx service
- name: Enabling Nginx service
  systemd:
   name: nginx
   enabled: yes
# Start Nginx service
- name: Starting Nginx service
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
# move the script that creates kibana user and password to tmp directory
- name: Move Kibana admin user script
  template:
    src: kibanaAdmin.sh
    dest: /tmp/createKibanaUser
    owner: root
    mode: 0744
# Install python Pexpect which is required to use the expect module
- name: Installing Python Pexpect
  apt:
    name: python-pexpect
    update_cache: yes
# Run the create kibana user script
- name: Create kibana admin user
  expect:
    command: bash /tmp/createKibanaUser
    responses:
      'Password:' : "{{kibana_password}}"
# Restart Nginx service to reflect the latest changes
- name: Restart Nginx service
  systemd:
   name: nginx
   state: started
   daemon_reload: yes

