---
#
# Installs Java 8 version
#
# Add the Java PPA repository
- name: Add Java repository
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
# Automatically accepts the oracle license
- name: Automatically select the Oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select
# Install Java 8
- name: Install the Java 8 package
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes